linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  goimports:
    local-prefixes: github.com/lawzava/go-pg-migrate
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 2
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - gci # Conflicts with gofumpt
    - interfacer # Deprecated
    - golint # Deprecated
    - maligned # Deprecated
    - scopelint # Deprecated

issues:
  exclude-rules:
    - path: examples/*
      linters:
        - gomnd
        - exhaustivestruct
        - gochecknoglobals
    - path: _test\.go
      linters:
        - exhaustivestruct
