package integration

import (
	"fmt"
	"strings"
	"testing"

	migrate "github.com/lawzava/go-pg-migrate/v3"
	"github.com/lawzava/go-pg-migrate/v3/integration/pgtest"
	"github.com/lawzava/go-pg-migrate/v3/migratetest"
)

// recorder captures Errorf calls so a test can assert that RoundTrip fails.
type recorder struct {
	*testing.T

	errors []string
}

func (r *recorder) Errorf(format string, args ...any) {
	r.errors = append(r.errors, fmt.Sprintf(format, args...))
}

func TestRoundTripPassesReversibleMigrations(t *testing.T) {
	t.Parallel()

	migrations := []migrate.Migration{
		table(1),
		{
			Version: 2,
			Name:    "everything",
			Up: migrate.SQL(`CREATE TYPE mood AS ENUM ('ok', 'sad');
				ALTER TABLE t1 ADD COLUMN m mood NOT NULL DEFAULT 'ok', ADD CONSTRAINT t1_id_positive CHECK (id > 0);
				CREATE INDEX t1_m ON t1 (m);
				CREATE FUNCTION one() RETURNS int LANGUAGE sql AS 'SELECT 1'`),
			Down: migrate.SQL(`DROP FUNCTION one(); DROP INDEX t1_m;
				ALTER TABLE t1 DROP CONSTRAINT t1_id_positive, DROP COLUMN m; DROP TYPE mood`),
		},
		// Irreversible migrations are applied and skipped.
		{Version: 3, Name: "irreversible", Up: migrate.SQL("CREATE TABLE kept (id int)")},
	}

	rec := &recorder{T: t}
	migratetest.RoundTrip(rec, pgtest.DB(t, "pgx"), migrations, migrate.Config{Schema: "ledger"})

	if len(rec.errors) > 0 {
		t.Fatalf("RoundTrip reported errors for clean migrations:\n%s", strings.Join(rec.errors, "\n"))
	}
}

func TestRoundTripCatchesIncompleteDown(t *testing.T) {
	t.Parallel()

	migrations := []migrate.Migration{{
		Version: 1,
		Name:    "leaky",
		Up:      migrate.SQL("CREATE TABLE a (id int); CREATE INDEX a_id ON a (id); CREATE TABLE b (id int)"),
		Down:    migrate.SQL("DROP TABLE a"),
	}}

	rec := &recorder{T: t}
	migratetest.RoundTrip(rec, pgtest.DB(t, "pgx"), migrations, migrate.Config{})

	if len(rec.errors) != 1 || !strings.Contains(rec.errors[0], "Down did not restore the schema") ||
		!strings.Contains(rec.errors[0], "+ relation public.b") {
		t.Fatalf("errors = %q, want one Down error naming table b", rec.errors)
	}
}

func TestRoundTripCatchesDefinitionChanges(t *testing.T) {
	t.Parallel()

	base := migrate.Migration{
		Version: 1,
		Name:    "objects",
		Up: migrate.SQL(`CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, a int, b int);
			CREATE FUNCTION f() RETURNS int LANGUAGE sql AS 'SELECT 1';
			CREATE VIEW v AS SELECT 1 AS x`),
		Down: migrate.SQL("DROP VIEW v; DROP FUNCTION f(); DROP TABLE t"),
	}

	// Each change is invisible to a snapshot of names and types alone, and
	// each Down is a no-op, so RoundTrip must report it.
	changes := map[string]string{
		"function body":   "CREATE OR REPLACE FUNCTION f() RETURNS int LANGUAGE sql AS 'SELECT 2'",
		"view definition": "CREATE OR REPLACE VIEW v AS SELECT 2 AS x",
		"identity kind":   "ALTER TABLE t ALTER COLUMN id SET GENERATED BY DEFAULT",
		"column order":    "ALTER TABLE t DROP COLUMN a; ALTER TABLE t ADD COLUMN a int",
	}

	for name, change := range changes {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			migrations := []migrate.Migration{base, {
				Version: 2, Name: name, Up: migrate.SQL(change), Down: migrate.SQL("SELECT 1"),
			}}

			rec := &recorder{T: t}
			migratetest.RoundTrip(rec, pgtest.DB(t, "pgx"), migrations, migrate.Config{})

			if len(rec.errors) == 0 || !strings.Contains(rec.errors[0], "version 2") {
				t.Fatalf("errors = %q, want a Down error for version 2", rec.errors)
			}
		})
	}
}

func TestRoundTripLongLedgerName(t *testing.T) {
	t.Parallel()

	// PostgreSQL shortens the generated primary key name of a 63-byte table,
	// so the ledger must be excluded by identity, not by a guessed name.
	config := migrate.Config{Table: strings.Repeat("l", 63)}

	rec := &recorder{T: t}
	migratetest.RoundTrip(rec, pgtest.DB(t, "pgx"), tables(1), config)

	if len(rec.errors) > 0 {
		t.Fatalf("RoundTrip reported errors for a clean migration:\n%s", strings.Join(rec.errors, "\n"))
	}
}
